In [6]:
class Student:
    id = 0
    def __init__(self, name, dept, age, cg):
        self.name = name
        self.dept = dept
        self.age = age
        self.cg = cg
        Student.id += 1
        self.id = Student.id
    def showDetails(self):
        print(f'''ID: {self.id}
Name: {self.name}
Department: {self.dept}
Age: {self.age}
CGPA: {self.cg}''')
    @classmethod
    def from_String(cls, text):
        a,b,c,d = text.split('-')
        stu = cls(a,b,c,d)
        return stu

s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [10]:
class Passenger:
    count = 0
    def __init__(self, name):
        self.name = name
        Passenger.count += 1
    def set_bag_weight(self, w):
        self.w = w
        if 21<=w<=50:
            self.fare = 500
        elif w>50:
            self.fare = 550
        else:
            self.fare = 450
    def printDetail(self):
        print(f'Name: {self.name}\nBus Fare: {self.fare} taka')

print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550 taka
=========================
Name: Carol
Bus Fare: 450 taka
=========================
Name: Mike
Bus Fare: 500 taka
=========================
Total Passenger: 3